name: Pareto's End
tagline: A procrastinator's ranting guide on development
markdown: kramdown
pygments: true
timezone: Europe/Paris
encoding: utf-8

excerpt_separator: "-- view more --"

paginate: 7
paginate_path: "archives/page:num"

exclude:
    - vendor
    - composer.json
    - composer.lock
    - README.md
    - Gemsfile

kramdown:
    input: GFM
    hard_wrap: false

gems:
    - typogruby
    - kramdown

info:
    display_name: Baptiste Clavié
    gravatar: http://www.gravatar.com/avatar/b0789133fae4698a351758835b4e4a6d.png
    email: clavie.b@gmail.com
    web: http://baptiste.clavié.net/
    
    twitter: talus_

    github:
        user: taluu
        repo: taluu/pareto-end
